# Author: Trevor Chaney
# Email: trevorchaney@gmail.com
# Website: https://tlc.is
# Remotes: https://github.com/trevorchaney/Dotfiles 
# Generated by git/update-backlinks.sh#!/bin/sh
# Consolidated installer for hooks
# - When run from the repo (file present), installs hooks by setting
#   `core.hooksPath` to the hooks in this repository.
# - When piped (curl | sh), downloads the repo archive and copies hooks
#   into `<repo>/.githooks` then sets `core.hooksPath`.
#
# Usage (defaults):
#   curl "https://raw.githubusercontent.com/trevorchaney/Dotfiles/master/git/install.sh" | sh -s -- [--repo owner/repo] [--branch branch] [--target path]

set -eu

usage() {
  cat <<EOF
Usage: curl URL | sh -s -- [--repo owner/repo] [--branch branch] [--target path]
Defaults: repo=trevorchaney/Dotfiles branch=master target=.
EOF
}

REPO="trevorchaney/Dotfiles"
BRANCH="master"
TARGET="."

DRY_RUN=0
CHECKSUM=""
while [ $# -gt 0 ]; do
  case "$1" in
    --repo) REPO="$2"; shift 2;;
    --branch) BRANCH="$2"; shift 2;;
    --target) TARGET="$2"; shift 2;;
    --dry-run) DRY_RUN=1; shift 1;;
    --checksum) CHECKSUM="$2"; shift 2;;
    --help) usage; exit 0;;
    *) break;;
  esac
done

# Determine if the script is running from a file on disk (local install)
if [ -f "$0" ]; then
  script_dir=$(cd "$(dirname "$0")" && pwd)
  src="$script_dir/.config/git/hooks"
  if [ -d "$src" ]; then
    # resolve git root for target and set hooksPath to the local hooks dir
    if git -C "$TARGET" rev-parse --show-toplevel >/dev/null 2>&1; then
      REPO_ROOT=$(git -C "$TARGET" rev-parse --show-toplevel)
      abs_src=$(cd "$src" && pwd)
      chmod +x "$abs_src"/* 2>/dev/null || true
      if [ "$DRY_RUN" -eq 1 ]; then
        echo "[dry-run] Would set core.hooksPath="$abs_src" for repository: $REPO_ROOT"
        echo "[dry-run] To revert: git -C $REPO_ROOT config --unset core.hooksPath"
        exit 0
      fi
      git -C "$REPO_ROOT" config core.hooksPath "$abs_src"
      echo "Installed hooks by setting core.hooksPath to $abs_src for repository: $REPO_ROOT"
      echo "To revert: git -C $REPO_ROOT config --unset core.hooksPath"
      exit 0
    else
      echo "Target '$TARGET' is not inside a git repository (or git not available)." >&2
      exit 1
    fi
  fi
fi

# If we reach here, assume piped execution (download archive and copy hooks)
tmpdir=$(mktemp -d 2>/dev/null || mktemp -d /tmp/hooksinstall.XXXXXX)
cleanup() { rm -rf "$tmpdir"; }
trap cleanup EXIT

echo "Downloading $REPO#$BRANCH ..."
if [ -n "$CHECKSUM" ]; then
  archive="$tmpdir/archive.tar.gz"
  curl -fsSL "https://github.com/$REPO/archive/refs/heads/$BRANCH.tar.gz" -o "$archive"
  # verify checksum if possible
  if command -v sha256sum >/dev/null 2>&1; then
    calc=$(sha256sum "$archive" | awk '{print $1}')
  elif command -v shasum >/dev/null 2>&1; then
    calc=$(shasum -a 256 "$archive" | awk '{print $1}')
  else
    echo "Checksum program not found (sha256sum or shasum). Cannot verify." >&2
    exit 1
  fi
  if [ "$calc" != "$CHECKSUM" ]; then
    echo "Checksum mismatch: expected $CHECKSUM but got $calc" >&2
    exit 1
  fi
  tar -xz -f "$archive" -C "$tmpdir"
else
  curl -fsSL "https://github.com/$REPO/archive/refs/heads/$BRANCH.tar.gz" | tar -xz -C "$tmpdir"
fi

hooks_dir=$(find "$tmpdir" -type d -path '*/git/.config/git/hooks' -print -quit)
if [ -z "$hooks_dir" ]; then
  echo "Could not find hooks directory inside archive. Checked: $tmpdir" >&2
  exit 1
fi

# Resolve the repository root for target
if git -C "$TARGET" rev-parse --show-toplevel >/dev/null 2>&1; then
  REPO_ROOT=$(git -C "$TARGET" rev-parse --show-toplevel)
else
  echo "Target '$TARGET' is not inside a git repository (or git not available)." >&2
  exit 1
fi


dest=$(cd "$REPO_ROOT" && pwd)/.githooks
if [ "$DRY_RUN" -eq 1 ]; then
  echo "[dry-run] Would copy hooks from $hooks_dir to $dest"
  echo "[dry-run] Would set core.hooksPath to $dest for repository: $REPO_ROOT"
  exit 0
fi

rm -rf "$dest"
mkdir -p "$dest"

cp -a "$hooks_dir/." "$dest/"
chmod +x "$dest"/* 2>/dev/null || true

git -C "$REPO_ROOT" config core.hooksPath "$dest"
echo "Installed hooks to $dest and set core.hooksPath for repository: $REPO_ROOT"
echo "To revert: git -C $REPO_ROOT config --unset core.hooksPath"

exit 0
