#!/bin/sh
# Abort commits with any of a list of terms.

term="localhost|127.0.0.1"
if ag "$term"; then
    echo
    echo "Found \"$term\" in your files..."
    echo "Remove all occurrences of \"$term\" before committing."
    exit 1
fi
